# Generated by Django 5.2.3 on 2025-07-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_dec', models.CharField(max_length=500)),
                ('recipe_rating', models.IntegerField()),
                ('recipe_directions', models.CharField(max_length=500)),
                ('recipe_ingredients', models.CharField(help_text="Enter a value split by ' , ' ex: <b nutritional yeast , soya sauce </b> ", max_length=500)),
            ],
        ),
    ]
