# Generated by Django 5.2.3 on 2025-07-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeslist',
            name='recipe_img',
            field=models.ImageField(default=2, upload_to='RecipeImages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeslist',
            name='recipe_ingredients',
            field=models.CharField(help_text="Enter a value split by ' , ' ex: <b> nutritional yeast , soya sauce </b> ", max_length=500),
        ),
    ]
