# Generated by Django 5.2.3 on 2025-07-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeslist_recipe_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeslist',
            name='recipe_img',
            field=models.ImageField(blank=True, null=True, upload_to='RecipeImages'),
        ),
    ]
