# Generated by Django 5.2.3 on 2025-07-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeslist_recipe_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipeRaquest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_img', models.ImageField(blank=True, null=True, upload_to='RecipeRequestImages')),
            ],
        ),
    ]
